### PR TITLE
updated phrases for School and Bus Locator

### PR DESCRIPTION
**Pull request by hcpss-vincevince1006**
Added terms for locator @hcpss-mbarger

### CODE REVIEW

**Comment by hcpss-mbarger** [comment]
"Attend" surprised me.  How do you see it used in a search phrase?

**Comment by hcpss-vincevince1006** [comment]
I could see searchers querying questions such as "what school does my child attend"

**Comment by hcpss-mbarger** [comment]
Good idea.

**Comment by hcpss-mbarger** [comment]
Thanks @hcpss-vincevince1006! The new CSV was deployed.

**Pull request merged**
